### ISSUE TITLE
BackupRestore without SetSourceReadOnly

### ISSUE THREAD

**Issue by techop** [ctrlbold/dbatools#3] opened 2016-01-08 16:06 UTC
I cannot find a way to perform Start-SqlMigration with the -BackupRestore method without it trying to set the source databases to read only. I have tried not specifying -SetSourceReadOnly and I have tried -SetSourceReadOnly:$false. How do you perform a SqlMigration without it modifying anything on the source server?

Thanks!

**Comment by ctrlbold** [comment] 2016-02-22 12:54
Hey techop,
Sorry for the delay. I am not able to reproduce this issue. What OS are you using? What SQL Server versions? Do you have the latest copy of dbatools? You can run Update-dbatools.

**Comment by ctrlbold** [comment] 2016-05-01 02:03
Closing because I never heard back and can't repro

**Closed by ctrlbold** 2016-05-01 02:03 UTC
